# -*- coding: utf-8 -*-
"""Datos de referencia del generador de datos demo (BI San Andres).

Derivados del set de gestion de referencia (VL, mayo 2026) que dejo Cesar en
SMOKE/ (no versionado). Los nombres estan RECOMBINADOS al azar en el generador
(apellido de una fila, nombre de otra): nunca viaja un par real.
Regenerable con el script de extraccion (sesion 2026-08-30).
"""

# (tipo_normalizado, grupo_servicio_normalizado, peso) - el generador matchea
# tipo->tipo_reclamo.nombre y, si no hay match, grupo->subarea.nombre.
TIPOS_REF: list[tuple[str, str, int]] = [
    ('falta de barrido o barrido deficiente', 'recol.residuos y limpieza', 983),
    ('retiro de restos de poda y/o jardineria domiciliaria', 'recol.residuos y limpieza', 397),
    ('retiro de escombros y/o restos de obra', 'recol.residuos y limpieza', 349),
    ('luminaria superior e inferior apagada durante la noche', 'alumbrado publico', 313),
    ('roedores en espacio publico', 'inconveniente con plagas en via publica', 205),
    ('retiro de muebles y/o electrodomesticos en desuso', 'recol.residuos y limpieza', 171),
    ('retiro de objetos/elementos en desuso', 'recol.residuos y limpieza', 152),
    ('falta de recoleccion de residuos organicos/humedos', 'recol.residuos y limpieza', 126),
    ('reparacion de semaforo', 'senalamiento vial', 123),
    ('bache en calle de asfalto', 'calles y veredas', 82),
    ('falta de recoleccion de residuos reciclables (programa dia verde)', 'recol.residuos reciclables', 57),
    ('limpieza/higienizacion de espacio publico', 'recol.residuos y limpieza', 57),
    ('reparacion/construccion de cordon', 'calles y veredas', 53),
    ('luminaria superior apagada durante la noche', 'alumbrado publico', 49),
    ('vaciado de cesto papelero', 'recol.residuos y limpieza', 49),
    ('arbol obstruye semaforo/luminaria/cartel/etc.', 'arbolado', 44),
    ('retiro de restos de poda y/o de arbolado publico', 'recol.residuos y limpieza', 39),
    ('inconvenientes con intervenciones de arbolado', 'arbolado', 31),
    ('otros ruidos molestos', 'inconvenientes con ruidos molestos', 29),
    ('luminaria superior e inferior encendida de dia', 'alumbrado publico', 27),
    ('luminaria inferior apagada durante la noche', 'alumbrado publico', 26),
    ('columna en mal estado/sin mantenimiento', 'alumbrado publico', 24),
    ('vehiculos abandonados', 'vehiculo abandonado', 23),
    ('cable cortado', 'mant. general', 22),
    ('reposicion de cesto papelero', 'recol.residuos y limpieza', 19),
    ('vehiculo mal estacionado', 'transito', 19),
    ('reparacion de vereda por obra mal terminada', 'mant. general', 19),
    ('musica fuera del horario habilitado', 'inconvenientes con ruidos molestos', 17),
    ('construccion de rampa de accesibilidad', 'calles y veredas', 16),
    ('yuyos/malezas/cesped no cortado/plantas que interfieren en via publica', 'recol.residuos y limpieza', 16),
    ('reparacion de rampa de accesibilidad', 'calles y veredas', 14),
    ('reposicion de contenedor', 'recol.residuos y limpieza', 14),
    ('colocacion de cesto papelero', 'recol.residuos y limpieza', 13),
    ('reparacion de vereda rota por empresa de servicio', 'inconvenientes con empresa de servicio p', 13),
    ('falta de habilitacion - actividad no declarada', 'irregularidades en actividades comercial', 12),
    ('reparacion de senal de transito', 'senalamiento vial', 12),
    ('repintado / reparacion de demarcacion vial en calle o cordon', 'senalamiento vial', 12),
    ('retiro de animales muertos en via publica', 'retiro de animales muertos', 12),
    ('luminaria superior intermitente', 'alumbrado publico', 11),
    ('repavimentacion de calle', 'calles y veredas', 11),
    ('ocupacion irregular de objetos y/o vehiculos', 'ocupacion irregular del espacio publico', 11),
    ('parada de colectivo en mal estado/sin mantenimiento', 'transito', 10),
    ('bache en calle de hormigon', 'calles y veredas', 9),
    ('otras plagas en espacio publico', 'inconveniente con plagas en via publica', 9),
    ('poste en mal estado/sin mantenimiento', 'mant. general', 9),
    ('reparacion de cuneta', 'calles y veredas', 9),
    ('reparacion de juegos/estaciones de ejercicio en parque/plaza', 'espacios verdes y plazas', 8),
    ('vaciado de contenedor', 'recol.residuos y limpieza', 8),
    ('presencia de plagas /roedores, cucarachas…etc)', 'inconveniente con olores y plagas en com', 7),
    ('reparacion de bebederos en parque/plaza', 'espacios verdes y plazas', 7),
    ('reparacion de senderos en parque/plaza', 'espacios verdes y plazas', 6),
    ('eventos irregulares en via publica', 'ocupacion irregular del espacio publico', 6),
    ('garita/puestos de diarios y/o flores irregulares', 'ocupacion irregular del espacio publico', 5),
    ('inconvenientes con el suministro de agua', 'inconvenientes con empresa de servicio p', 5),
    ('reparacion de rejas, bancos, mesas y sillas en parque/plaza', 'espacios verdes y plazas', 5),
    ('personal de empresa de recoleccion con conductas indebidas', 'inconvenientes con empresa de servicio p', 5),
    ('derrame toxico o material riesgoso', 'contaminacion por derrames toxicos o agu', 4),
    ('obras fuera del horario permitido', 'inconvenientes con ruidos molestos', 4),
    ('remocion de volquete abandonado o mal dispuesto', 'transito', 4),
    ('ruidos molestos por carga y descarga', 'inconvenientes con ruidos molestos', 4),
    ('venta de productos vencidos o en mal estado', 'higiene y seguridad – comercio/industria', 4),
    ('irregularidades con punto verde', 'recol.residuos reciclables', 4),
    ('abejas en espacio publico', 'inconveniente con plagas en via publica', 3),
    ('camion de recoleccion que incumple normas de transito', 'recol.residuos y limpieza', 3),
    ('construccion de cuneta', 'calles y veredas', 3),
    ('musica/bares no habilitados', 'inconvenientes con ruidos molestos', 3),
    ('pasacalles en via publica', 'ocupacion irregular del espacio publico', 3),
    ('reparacion de cesto papelero', 'recol.residuos y limpieza', 3),
    ('acopio de cartoneros en espacio publico', 'recol.residuos y limpieza', 3),
    ('fumadores en espacios no permitidos', 'irregularidades en actividades comercial', 3),
    ('agua servida en via publica', 'contaminacion por derrames toxicos o agu', 2),
    ('falta de higiene', 'higiene y seguridad – comercio/industria', 2),
    ('inconvenientes con las tareas de guardian de plaza', 'espacios verdes y plazas', 2),
    ('luminaria inferior intermitente', 'alumbrado publico', 2),
    ('venta ilegal en via publica', 'irregularidades en actividades comercial', 2),
    ('yuyos/malezas/cesped no cortado/plantas', 'espacios verdes y plazas', 2),
    ('bache en calle de adoquines', 'calles y veredas', 2),
    ('hidrolavado por grafitis/pegatinas', 'senalamiento vial', 2),
    ('instalacion de cartel nomenclador de calle', 'senalamiento vial', 2),
    ('irregularidades en la disposicion de residuos humedos/organicos', 'recol.residuos y limpieza', 2),
    ('reparacion de cartel nomenclador de calle', 'senalamiento vial', 2),
    ('reparacion de lomo de burro o reductor de velocidad', 'calles y veredas', 2),
    ('reparacion o dano de caniles en parque/plaza', 'espacios verdes y plazas', 2),
    ('tapa faltante/deteriorada', 'alumbrado publico', 2),
    ('venta no habilitada de bebidas alcoholicas', 'irregularidades en actividades comercial', 2),
    ('instalacion de caniles en parque/plaza', 'espacios verdes y plazas', 2),
    ('incon. en camaras de inspec. de empresa de servicio publico en calle/vereda', 'inconvenientes con empresa de servicio p', 2),
    ('actividad fuera del horario habilitado', 'irregularidades en actividades comercial', 1),
    ('avispas en espacio publico', 'inconveniente con plagas en via publica', 1),
    ('inconvenientes con los horarios de apertura y cierre de parque/plaza', 'espacios verdes y plazas', 1),
    ('lavado de contenedor', 'recol.residuos y limpieza', 1),
    ('malos olores', 'inconveniente con olores y plagas en com', 1),
    ('nivelacion de tapa de empresa de servicio publico en calle/vereda', 'inconvenientes con empresa de servicio p', 1),
    ('personal de empresa de recoleccion realiza pedido de dadivas', 'inconvenientes con empresa de servicio p', 1),
    ('vaciado de cesto papelero en parque/plaza', 'espacios verdes y plazas', 1),
    ('carga y descarga fuera del horario habilitado', 'irregularidades en actividades comercial', 1),
    ('reparacion de darsena para ascenso / descenso de colectivos', 'transito', 1),
    ('reparacion de elementos en tuneles / puentes', 'senalamiento vial', 1),
    ('ruidos molestos por aires acondicionados', 'inconvenientes con ruidos molestos', 1),
    ('venta de bebidas alcoholicas fuera del horario habilitado', 'irregularidades en actividades comercial', 1),
    ('error en los datos de la licencia emitida: reimpresion/duplicado', 'licencia de conducir', 1),
    ('instalacion de bancos, mesas y sillas en parque/plaza', 'espacios verdes y plazas', 1),
    ('reparacion de monumento/obra de arte en parque/plaza', 'espacios verdes y plazas', 1),
    ('colocacion de reductores de velocidad', 'transito', 1),
    ('instalacion de bebederos en parque/plaza', 'espacios verdes y plazas', 1),
    ('instalacion de cestos de basura en parque/plaza', 'espacios verdes y plazas', 1),
    ('instalacion de juegos en parque/plaza', 'espacios verdes y plazas', 1),
    ('refugio de colectivo en mal estado/sin mantenimiento', 'calles y veredas', 1),
    ('reparacion de calle rota por empresa de servicio', 'inconvenientes con empresa de servicio p', 1),
    ('reparacion de fuentes en parque/plaza', 'espacios verdes y plazas', 1),
    ('reparacion de tapa de empresa de servicio publico en calle/vereda', 'inconvenientes con empresa de servicio p', 1),
    ('toldos/cerramientos/estructuras irregulares en via publica', 'ocupacion irregular del espacio publico', 1),
    ('vehiculo obstruyendo garage', 'transito', 1),
]

# (nombre_localidad, peso, lat, lon, radio_m) - id resuelto por nombre en runtime.
LOCALIDADES_REF: list[tuple[str, int, float, float, int]] = [
    ('Olivos', 1205, -34.5075, -58.49, 1000),
    ('Florida', 791, -34.5305, -58.501, 800),
    ('Munro', 478, -34.5315, -58.523, 700),
    ('Vicente López', 372, -34.526, -58.475, 800),
    ('Florida Oeste', 291, -34.531, -58.514, 700),
    ('Villa Martelli', 251, -34.552, -58.512, 700),
    ('Carapachay', 205, -34.525, -58.529, 600),
    ('La Lucila', 172, -34.498, -58.482, 550),
    ('Villa Adelina', 123, -34.5195, -58.543, 700),
]

APELLIDOS: list[str] = [
    'Fernandez',
    'Rodriguez',
    'Gonzalez',
    'Lopez',
    'Gomez',
    'Martinez',
    'Sanchez',
    'Garcia',
    'Doat',
    'Perez',
    'Alvarez',
    'Suarez',
    'Calvetti',
    'Zammarano',
    'Beckmann',
    'Vazquez',
    'Felgueroso',
    'Lancman',
    'Smidth',
    'Sparrow',
    'Roman',
    'Ramirez',
    'Ruiz',
    'Paez',
    'Beja',
    'Blanco',
    'Solé',
    'Güiraldes',
    'Castaño',
    'Ortiz',
    'Braga',
    'Duran',
    'Ferreyra',
    'Osso',
    'Barreiro',
    'Via',
    'Martin',
    'Cisneros',
    'Silva',
    'Alonso',
    'Ferrari',
    'Ruggieri',
    'Romero',
    'Rubio',
    'Lopez Omaña',
    'Negrotti',
    'Fabiano',
    'Ale',
    'Duva',
    'Gomar',
    'Benitez',
    'Marin',
    'Tomasini',
    'Nemi',
    'Galante',
    'Cabrera',
    'Gil',
    'Lorenzo',
    'Acacia',
    'Pacotto',
    'Oroñe Marcote',
    'Battista',
    'Calvo',
    'Bryant',
    'Lois Dierna',
    'Roisman',
    'Kenny',
    'Cacchione',
    'De Siervi',
    'Vivas Maqueda',
    'Diaz',
    'Coto',
    'Dominguez',
    'Coucheiro',
    'Carmona',
    'Morelli',
    'Moretti',
    'De Reira',
    'Moreno',
    'Vila',
    'Crudo',
    'Florida Oeste',
    'Mendoza',
    'Altimari',
    'Niro',
    'Cattaneo',
    'Bobbio',
    'Medina',
    'Pablos',
    'Villalba Ramirez',
    'Bergara',
    'Guarna',
    'Compagnucci',
    'Janza',
    'Mazzucco',
    'Caruso',
    'Relevamiento Auditoria',
    'Mansilla',
    'De Angelis',
    'Ferrario',
    'Otero',
    'Cohen',
    'Maraggi',
    'Beltrame',
    'Cincer',
    'Bravo',
    'Molinari',
    'Castillo',
    'Vera',
    'Rios',
    'Passero',
    'Aguirre',
    'Giuffrida',
    'Castro',
    'Singer',
    'Merallo',
    'Guerrero',
    'Nieto',
    'Muñoz',
    'Quinteros',
    'Lema',
    'Mohamad',
    'Anduaga',
    'Fink',
    'Prieto',
    'Cardozo',
    'Morales',
    'Iturriza',
    'Bartolino',
    'Gomez Ares',
    'Acosta',
    'Pereyra',
    'Puente',
    'Perez Keogan',
    'Garcia Morillo',
    'Martul Sainz',
    'Herrera',
    'Gifuni',
    'Pistone',
    'Bulla',
    'Cerri',
    'Ruveda',
    'Haug',
    'Valente',
    'Vacca',
    'San Emeterio',
    'Brunengraber',
    'López',
    'Venturini',
    'Barreneche',
    'Mora',
    'Prado',
    'Flaherty',
    'Stanic',
    'Castrilli',
    'La Terza',
    'Juan',
    'Ibañez',
    'Kazanski',
    'Rainero',
    'Cancilieri',
    'Rebollo',
    'Gallo',
    'Doubell',
    'Montes',
    'Barreiro Buceta',
    'Orvieto',
    'Pazos',
    'Taylor',
    'Villalba',
]

NOMBRES: list[str] = [
    'Maria',
    'Marcela',
    'Alicia',
    'Graciela',
    'Silvia',
    'Ana Maria',
    'Veronica',
    'Susana',
    'Adriana',
    'Maria Alejandra',
    'Florencia',
    'Juan Carlos',
    'Roberto',
    'Maria Cristina',
    'Patricia',
    'Ana',
    'Andrea',
    'Camila',
    'Victor',
    'Elena',
    'Marta',
    'Claudio',
    'Cristina',
    'Mariana',
    'Fernanda',
    'Liliana',
    'Maria Elena',
    'Cecilia',
    'Carlos',
    'Gabriel',
    'Pablo',
    'Silvina',
    'Nicolas',
    'Claudia',
    'Romina',
    'Patricia Monica',
    'Norberto',
    'Juan',
    'Monica',
    'Maria Fernanda',
    'Alberto',
    'Armando Daniel',
    'Beatriz',
    'Ricardo',
    'Fernando',
    'Juan Jose',
    'Guillermo',
    'Maria Laura',
    'Marisa',
    'Luciana',
    'Maria Florencia',
    'Horacio Adrian',
    'Juan Cruz',
    'Dario',
    'Silvia Alejandra',
    'Jorge Diego',
    'Mariela',
    'Viviana',
    'Gabriela',
    'Antonio',
    'Maria Eugenia',
    'Silvia Yolanda',
    'Hernan',
    'Micaela',
    'Carolina',
    'Amelia',
    'Maria Cecilia',
    'Daniel',
    'Valeria',
    'Federico',
    'Miguel',
    'Sergio',
    'Maria Isabel',
    'Lidia',
    'Hector',
    'Julieta',
    'Eduardo',
    'Juan Manuel',
    'Margarita',
    'Nelida',
    'Norma',
    'Laura',
    'Martin',
    'Marcelo',
    'Karina',
    'Matias Nicolas',
    'Gustavo Adolfo',
    'Romina Bárbara',
    'Jorge',
    'Adriana Mabel',
    'Mariano',
    'Alfredo',
    'Matias Sebastian',
    'Alejandra',
    'Rosa',
    'Nilda Beatriz',
    'Mirta',
    'Roxana',
    'Analia',
    'Sara',
    'Francisco',
    'Juan Pablo',
    'Ivana Mariel',
    'Lucia',
    'Juan Martin',
    'Carlos Fernando',
    'Maria Mercedes',
    'Graciela Beatriz',
    'Jose Maria',
    'Roberto Gustavo',
    'Marcela Lucrecia',
    'Norma Patricia',
    'Maria Dolores',
    'Jesus',
    'Maria Ester',
    'Lucrecia',
    'Javier',
    'Maria Rosa',
    'Gabriela Alejandra',
    'Jose Luis',
    'Diego',
    'Sebastian',
    'Maria Ines',
    'Santiago',
    'Maria Marta',
    'Cesar',
    'Maria Teresa',
    'Oscar',
    'Mirian Vanesa',
    'Gisela Natalia',
    'Leila Ayelen',
    'Maria Jose',
    'Octavio',
    'Cintia Mara',
    'Diana',
    'Diefo',
    'Lucas',
    'Manuel Rodrigo',
    'Ramona',
    'Relevamiento Auditoria',
    'Vanina',
    'Miguel Angel',
    'Luciano',
    'Osvaldo Luis',
    'Oscar Ernesto',
    'Gustavo Gabriel',
    'Azucena',
    'Estela',
    'Maximiliano',
    'Natalia',
    'Maria Luisa',
    'Pablo Cirilo',
    'Cristian Ricardo',
    'Liliana Noemi',
    'Gustavo',
    'Leonardo Marcelo',
    'Stella Maris',
    'Yamila Belen',
    'Betina Isabel',
    'Adriana Laura',
    'Nadia Macarena',
    'Claudia Hebe',
    'German Octavio',
    'Maria Susana',
    'Rodolfo',
    'Amalia Luiso',
    'Nahuel',
    'Nuria',
    'Mario Daniel',
    'Daniel Alejandro',
]

